CREATE TABLE `Book`` (
  `Book_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Book_name` VARCHAR(30) NOT NULL,
  `price` VARCHAR(30) NOT NULL,
  `Quantity` VARCHAR(60) NOT NULL,
   PRIMARY KEY (`Bookid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;